version: "3.8"

services:
  minecraft-java:
    container_name: minecraft-java
    hostname: minecraft-java
    image: 'itzg/minecraft-server'
    ports:
      - "25565:25565" 
    tty: true
    stdin_open: true
    networks:
      myBridge:
        ipv4_address: 172.21.0.3
    environment:
      EULA: "TRUE"
      VERSION: "1.7.10"
    volumes:
    # make this local so it's easy to change/backup data
      - '/my_local_DIR/docker_dirs/minecraft_java:/data'
    restart: unless-stopped

networks:
  myBridge:
    external: true

volumes:
  minecraft_java:
    external: true
